// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXHUjcagDgAwBl5LzQnJ4r8CsEepYI-8',
    appId: '1:992616813573:web:c78d2bf8cf1514a7f4386c',
    messagingSenderId: '992616813573',
    projectId: 'animeapp-608c0',
    authDomain: 'animeapp-608c0.firebaseapp.com',
    storageBucket: 'animeapp-608c0.firebasestorage.app',
    measurementId: 'G-LS3YP624XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjFr0Rk199DeoyON-keqQEMa2DM1Upz4',
    appId: '1:992616813573:android:bf30a483476174ebf4386c',
    messagingSenderId: '992616813573',
    projectId: 'animeapp-608c0',
    storageBucket: 'animeapp-608c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJNFRgixuZhLj2qr4EDnMNqw7A3Bmv9Y',
    appId: '1:992616813573:ios:d52270b0074ed89bf4386c',
    messagingSenderId: '992616813573',
    projectId: 'animeapp-608c0',
    storageBucket: 'animeapp-608c0.firebasestorage.app',
    iosClientId: '992616813573-n85r7og0v9134jsg2dfm8hbla35augj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJNFRgixuZhLj2qr4EDnMNqw7A3Bmv9Y',
    appId: '1:992616813573:ios:d52270b0074ed89bf4386c',
    messagingSenderId: '992616813573',
    projectId: 'animeapp-608c0',
    storageBucket: 'animeapp-608c0.firebasestorage.app',
    iosClientId: '992616813573-n85r7og0v9134jsg2dfm8hbla35augj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQXHUjcagDgAwBl5LzQnJ4r8CsEepYI-8',
    appId: '1:992616813573:web:a8c967143237245af4386c',
    messagingSenderId: '992616813573',
    projectId: 'animeapp-608c0',
    authDomain: 'animeapp-608c0.firebaseapp.com',
    storageBucket: 'animeapp-608c0.firebasestorage.app',
    measurementId: 'G-FVLH7P7NC3',
  );
}
